version: '3'
services:
  cadot.info-getLinks:
    image: cadotinfo/symfony5
    container_name: cadot.info-getLinks
    volumes:
      - .:/app
    networks:
      - web
    restart: always
    ports:
      - 80


networks:
  web:
    external: true
